### PR TITLE
[build-tools] add project id validation

### PR DESCRIPTION
**Pull request by wkozyra95**
# Why

On the recent github sync @FiberJW pointed out that it's easy to configure a project where projectId in app config is different than real project id.

The same issue exists for non github build if user have some env variables set only locally but not on the EAS Build worker.

# How

I'm open to suggestions, I see 2 alternatives:
- (currently implemented in this PR) Mark the build phase as a warning and log an error, but do not abort the build process
- Throw an error when this happens.

There are also few other open questions:
- do we want to explain potential scenarios why this might happen or just that there is a mismatch?
- do we want to validate any other fileds like that e.g. slug/owner.
- do we want to limit this validation to managed projects only?

# Test Plan

tested with local builds by setting EAS_BUILD_PROJECT_ID manually

### CODE REVIEW

**Comment by wkozyra95** [comment]
cc @brentvatne

**Review by szdziedzic — COMMENTED** [review]
Marking the build phase as a warning seems OK to me. Throwing an error here might be overkill in this context.

I assume we probably want to provide the user with some additional information about the issue except the very generic error message `Project id defined in app.json does not match current projectId in app.json/app.config.js`. Adding an FYI page explaining scenarios where such an issue can happen and linking to it from here might be a good approach.

**Comment by dsokal** [comment]
Is there a way to check the potential mismatch in EAS CLI? I suppose we could compare the `projectId` resolved the current way and one resolved only using only env variables from eas.json. The downside of this approach is that someone could be using EAS secrets for storing the project id. This generally feels wrong but I can see there are some ppl using it this way. If we had the validation in EAS CLI, I think we could use a prompt to confirm that the user wants to run a build. At the same time, my idea does not mean this PR is not necessary. But means, I'd lean towards printing a warning, and not throwing an error.

**Comment by wkozyra95** [comment]
@dsokal 

We can't really detect that, as you already mentioned for EAS CLI builds EAS Secrets is the issue and for GitHub builds we can't detect that any earlier.

**Comment by brentvatne** [comment]
> On the recent github sync @FiberJW pointed out that it's easy to configure a project where projectId in app config is different than real project id.

> I'm open to suggestions, I see 2 alternatives:
> (currently implemented in this PR) Mark the build phase as a warning and log an error, but do not abort the build process
> Throw an error when this happens.

I believe we should throw an error, and then revisit that if we find that this somehow breaks "reasonable" use cases. I think an error is better because it's very easy to miss a warning, and a mismatched project id could have unexpected consequences at runtime with APIs that depend on the project id, eg: with push notifications (maybe also eas update? unsure)

> There are also few other open questions:
>
> do we want to explain potential scenarios why this might happen or just that there is a mismatch?

yeah let's link to the FYI page you created along with the error. let's print out the evaluated project id and the expected project id, explain that they don't match, and link to your fyi page, then error the build.

> do we want to validate any other fields like that e.g. slug/owner.

I'd love to be able to get rid of the owner field, but I'm not sure what is left to be able to support that. `owner` is just repeating information that we should already know via the project id, afaik. cc @wschurman - I'm not sure what the state is of being able to move away from this.

I don't believe we're depending on the slug for anything at runtime anymore.. so maybe that is something that is better suited for a warning. that said, I can't think of why anyone would *want* to have a mismatched slug and it's possible that this could indicate something else is going to be very wrong with their build.

> do we want to limit this validation to managed projects only?

I believe this is always set in **app.json/app.config.js** regardless of whether it's a managed or bare app, and that the value isn't mirrored anywhere in the native app config except at build time when we embed the app config. so i think we can apply the same validation in both cases, because the side effects if it's wrong could be the same.

**Comment by wkozyra95** [comment]
> I believe we should throw an error, and then revisit that if we find that this somehow breaks "reasonable" use cases.

I don't think there are reasonable use cases, but I was concerned about cases where it does not matter for users what project id is set inside the apk/ipa, but we would still break their builds.

I ended up adding warning when project id is not defined, and throwing error if it is defined, but values do not match

**Review by szdziedzic — APPROVED** [review]
It looks good, although I think @brentvatne suggested `...let's print out the evaluated project id and the expected project id...`. I don't see you are doing it in your code in the current version. 

What do you think about adding this print?

**Pull request merged**
